// goPay Design Token System
// Single source of truth for all visual values
// All inline styles across the app should reference these tokens

export const colors = {
  brand: {
    primary: '#16a34a',
    light: '#4ade80',
    dim: 'rgba(22,163,74,0.12)',
    border: 'rgba(22,163,74,0.2)',
    glow: 'rgba(22,163,74,0.15)',
  },
  surface: {
    base: '#080d08',
    card: '#111711',
    elevated: '#1a231a',
    input: '#0f160f',
    overlay: 'rgba(0,0,0,0.6)',
  },
  border: {
    subtle: 'rgba(255,255,255,0.08)',
    emphasis: 'rgba(255,255,255,0.15)',
    focus: 'rgba(22,163,74,0.5)',
  },
  text: {
    primary: '#ffffff',
    secondary: 'rgba(255,255,255,0.55)',
    tertiary: 'rgba(255,255,255,0.30)',
    disabled: 'rgba(255,255,255,0.20)',
    inverse: '#080d08',
  },
  semantic: {
    success: '#22c55e',
    successDim: 'rgba(34,197,94,0.12)',
    error: '#ef4444',
    errorDim: 'rgba(239,68,68,0.12)',
    warning: '#f59e0b',
    warningDim: 'rgba(245,158,11,0.12)',
    info: '#3b82f6',
    infoDim: 'rgba(59,130,246,0.12)',
  },
} as const;

export const spacing = {
  1: '4px',
  2: '8px',
  3: '12px',
  4: '16px',
  5: '20px',
  6: '24px',
  8: '32px',
  10: '40px',
  12: '48px',
  16: '64px',
} as const;

export const radius = {
  sm: '8px',
  md: '12px',
  lg: '16px',
  xl: '20px',
  '2xl': '24px',
  '3xl': '28px',
  full: '9999px',
} as const;

export const typography = {
  display1: { fontSize: '40px', fontWeight: 800, letterSpacing: '-2px', lineHeight: '1.0' },
  display2: { fontSize: '32px', fontWeight: 700, letterSpacing: '-1.5px', lineHeight: '1.1' },
  title1: { fontSize: '24px', fontWeight: 700, letterSpacing: '-0.5px', lineHeight: '1.2' },
  title2: { fontSize: '20px', fontWeight: 600, letterSpacing: '-0.3px', lineHeight: '1.3' },
  body1: { fontSize: '16px', fontWeight: 400, lineHeight: '1.5' },
  body2: { fontSize: '14px', fontWeight: 400, lineHeight: '1.5' },
  caption1: { fontSize: '12px', fontWeight: 500, lineHeight: '1.4' },
  caption2: { fontSize: '11px', fontWeight: 400, lineHeight: '1.4' },
  label: { fontSize: '13px', fontWeight: 500, lineHeight: '1.3' },
} as const;

export const shadow = {
  card: '0 2px 12px rgba(0,0,0,0.4)',
  elevated: '0 8px 32px rgba(0,0,0,0.6)',
  glow: '0 0 24px rgba(22,163,74,0.2)',
} as const;

// Swahili / English copy tokens — single source for bilingual strings
export const copy = {
  sw: {
    appName: 'goPay',
    tagline: 'Pochi yako ya dijitali Tanzania',
    balance: 'Salio Lako',
    sendMoney: 'Tuma Pesa',
    receiveMoney: 'Pokea Pesa',
    payBill: 'Lipa Bili',
    addFunds: 'Weka Pesa',
    withdraw: 'Toa Pesa',
    confirm: 'Thibitisha',
    cancel: 'Ghairi',
    continue: 'Endelea',
    back: 'Rudi',
    done: 'Imekamilika',
    loading: 'Inapakia...',
    error: 'Hitilafu imetokea',
    success: 'Imefaulu',
    home: 'Nyumbani',
    pay: 'Lipa',
    money: 'Pesa',
    more: 'Zaidi',
    rewards: 'Zawadi',
    transactions: 'Shughuli',
    settings: 'Mipangilio',
    support: 'Msaada',
    recentActivity: 'Shughuli za Hivi Karibuni',
    quickActions: 'Vitendo vya Haraka',
    greeting_morning: 'Habari za asubuhi',
    greeting_afternoon: 'Habari za mchana',
    greeting_evening: 'Habari za jioni',
    fee: 'Ada',
    total: 'Jumla',
    amount: 'Kiasi',
    recipient: 'Mpokeaji',
    pin: 'PIN yako',
    enterPin: 'Ingiza PIN yako ya siri',
    phoneNumber: 'Namba yako ya simu',
    verifyPhone: 'Thibitisha namba yako',
    otpSent: 'Tumesend msimbo kwa',
    yourName: 'Jina lako',
    welcome: 'Karibu',
    getStarted: 'Anza Sasa',
    skipStep: 'Ruka hatua hii',
    alreadyHaveAccount: 'Tayari una akaunti?',
    signIn: 'Ingia',
    moneySent: 'Pesa Imetumwa!',
    moneyReceived: 'Umepokea Pesa!',
    transactionRef: 'Kumbukumbu',
    sendAgain: 'Tuma tena',
    shareReceipt: 'Shiriki risiti',
    backHome: 'Rudi nyumbani',
    earnCashback: 'Pata cashback kwa kila malipo',
    cashbackRate: 'Cashback ya 15%',
    securePayment: 'Malipo salama na yaliyolindwa',
    firstTimeRecipient: 'Mara ya kwanza unamtumia',
    unusualTime: 'Unatuma wakati usio wa kawaida',
    kycUpgradeTitle: 'Ongeza mipaka yako',
    kycUpgradeDesc: 'Thibitisha utambulisho wako ndani ya sekunde 30',
    dailyLimitReached: 'Umefika kikomo cha siku',
    referFriend: 'Alika Rafiki',
    referralBonus: 'Pata TZS 1,000 kwa kila rafiki',
    disputeTransaction: 'Pingana na malipo haya',
  },
  en: {
    appName: 'goPay',
    tagline: 'Tanzania\'s complete financial super app',
    balance: 'Your Balance',
    sendMoney: 'Send Money',
    receiveMoney: 'Receive Money',
    payBill: 'Pay Bill',
    addFunds: 'Add Funds',
    withdraw: 'Withdraw',
    confirm: 'Confirm',
    cancel: 'Cancel',
    continue: 'Continue',
    back: 'Back',
    done: 'Done',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    home: 'Home',
    pay: 'Pay',
    money: 'Money',
    more: 'More',
    rewards: 'Rewards',
    transactions: 'Transactions',
    settings: 'Settings',
    support: 'Support',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    fee: 'Service fee',
    total: 'Total',
    amount: 'Amount',
    recipient: 'Recipient',
    pin: 'Your PIN',
    enterPin: 'Enter your secret PIN',
    phoneNumber: 'Your phone number',
    verifyPhone: 'Verify your number',
    otpSent: 'We sent a code to',
    yourName: 'Your name',
    welcome: 'Welcome',
    getStarted: 'Get Started',
    skipStep: 'Skip this step',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    moneySent: 'Money Sent!',
    moneyReceived: 'Money Received!',
    transactionRef: 'Reference',
    sendAgain: 'Send again',
    shareReceipt: 'Share receipt',
    backHome: 'Back to home',
    earnCashback: 'Earn cashback on every payment',
    cashbackRate: '15% cashback rewards',
    securePayment: 'Secured and encrypted payment',
    firstTimeRecipient: 'First time sending to this contact',
    unusualTime: 'You\'re sending at an unusual time',
    kycUpgradeTitle: 'Increase your limits',
    kycUpgradeDesc: 'Verify your identity in 30 seconds',
    dailyLimitReached: 'Daily limit reached',
    referFriend: 'Refer a Friend',
    referralBonus: 'Earn TZS 1,000 per referral',
    disputeTransaction: 'Dispute this transaction',
  },
} as const;

export type Language = 'sw' | 'en';
export type CopyKey = keyof typeof copy.sw;

export function t(key: CopyKey, lang: Language = 'sw'): string {
  return copy[lang][key] as string;
}

export default { colors, spacing, radius, typography, shadow, copy, t };
