/* AUTOGENERATED FILE — override via VITE_SUPABASE_PROJECT_ID / VITE_SUPABASE_ANON_KEY */

export const projectId: string =
  (import.meta.env.VITE_SUPABASE_PROJECT_ID as string) || "smoaclzhvavtuzqgogse";

export const publicAnonKey: string =
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtb2FjbHpodmF2dHV6cWdvZ3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMzE3NjUsImV4cCI6MjA3ODkwNzc2NX0.hcSgbMhfCrPIce1xg7TQoXdR2G_GGSSOdjdqWDIy3U4";